baseURL = "https://mmontielpz.github.io/"
languageCode = "en-us"
title = "Miguel Lopez"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  mainSections = []
  showPostList = false
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableScrollToTop = false
  hideMeta = false
  showToc = false
  showPostNavLinks = false
  showBreadCrumbs = false
  showReadingTime = false
  showWordCount = false
  showShareButtons = false

  [params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon.svg"
    favicon32x32 = "favicon.svg"
    apple_touch_icon = "favicon.svg"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
