baseURL = "https://mmontielpz.github.io/"
languageCode = "en-us"
title = "Miguel Lopez"
theme = "PaperMod"

enableRobotsTXT = true

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
